import { STATIC_PROVINCES } from "./staticProvinces";

export type StaticCity = {
  id: string;
  provinceId: string;
  provinceName: string;
  type: string;
  name: string;
};

const RAW_STATIC_CITIES: Record<string, { type: string; name: string }[]> = {
  "1": [
    { type: "Kabupaten", name: "Badung" },
    { type: "Kabupaten", name: "Bangli" },
    { type: "Kabupaten", name: "Buleleng" },
    { type: "Kabupaten", name: "Gianyar" },
    { type: "Kabupaten", name: "Jembrana" },
    { type: "Kabupaten", name: "Karangasem" },
    { type: "Kabupaten", name: "Klungkung" },
    { type: "Kabupaten", name: "Tabanan" },
    { type: "Kota", name: "Denpasar" },
  ],
  "2": [
    { type: "Kabupaten", name: "Bangka" },
    { type: "Kabupaten", name: "Bangka Barat" },
    { type: "Kabupaten", name: "Bangka Selatan" },
    { type: "Kabupaten", name: "Bangka Tengah" },
    { type: "Kabupaten", name: "Belitung" },
    { type: "Kabupaten", name: "Belitung Timur" },
    { type: "Kota", name: "Pangkal Pinang" },
  ],
  "3": [
    { type: "Kabupaten", name: "Lebak" },
    { type: "Kabupaten", name: "Pandeglang" },
    { type: "Kabupaten", name: "Serang" },
    { type: "Kabupaten", name: "Tangerang" },
    { type: "Kota", name: "Cilegon" },
    { type: "Kota", name: "Serang" },
    { type: "Kota", name: "Tangerang" },
    { type: "Kota", name: "Tangerang Selatan" },
  ],
  "4": [
    { type: "Kabupaten", name: "Bengkulu Selatan" },
    { type: "Kabupaten", name: "Bengkulu Tengah" },
    { type: "Kabupaten", name: "Bengkulu Utara" },
    { type: "Kabupaten", name: "Kaur" },
    { type: "Kabupaten", name: "Kepahiang" },
    { type: "Kabupaten", name: "Lebong" },
    { type: "Kabupaten", name: "Mukomuko" },
    { type: "Kabupaten", name: "Rejang Lebong" },
    { type: "Kabupaten", name: "Seluma" },
    { type: "Kota", name: "Bengkulu" },
  ],
  "5": [
    { type: "Kabupaten", name: "Bantul" },
    { type: "Kabupaten", name: "Gunungkidul" },
    { type: "Kabupaten", name: "Kulon Progo" },
    { type: "Kabupaten", name: "Sleman" },
    { type: "Kota", name: "Yogyakarta" },
  ],
  "6": [
    { type: "Kabupaten", name: "Kepulauan Seribu" },
    { type: "Kota Administrasi", name: "Jakarta Barat" },
    { type: "Kota Administrasi", name: "Jakarta Pusat" },
    { type: "Kota Administrasi", name: "Jakarta Selatan" },
    { type: "Kota Administrasi", name: "Jakarta Timur" },
    { type: "Kota Administrasi", name: "Jakarta Utara" },
  ],
  "7": [
    { type: "Kabupaten", name: "Boalemo" },
    { type: "Kabupaten", name: "Bone Bolango" },
    { type: "Kabupaten", name: "Gorontalo" },
    { type: "Kabupaten", name: "Gorontalo Utara" },
    { type: "Kabupaten", name: "Pohuwato" },
    { type: "Kota", name: "Gorontalo" },
  ],
  "8": [
    { type: "Kabupaten", name: "Batang Hari" },
    { type: "Kabupaten", name: "Bungo" },
    { type: "Kabupaten", name: "Kerinci" },
    { type: "Kabupaten", name: "Merangin" },
    { type: "Kabupaten", name: "Muaro Jambi" },
    { type: "Kabupaten", name: "Sarolangun" },
    { type: "Kabupaten", name: "Tanjung Jabung Barat" },
    { type: "Kabupaten", name: "Tanjung Jabung Timur" },
    { type: "Kabupaten", name: "Tebo" },
    { type: "Kota", name: "Jambi" },
    { type: "Kota", name: "Sungai Penuh" },
  ],
  "9": [
    { type: "Kabupaten", name: "Bandung" },
    { type: "Kabupaten", name: "Bandung Barat" },
    { type: "Kabupaten", name: "Bekasi" },
    { type: "Kabupaten", name: "Bogor" },
    { type: "Kabupaten", name: "Ciamis" },
    { type: "Kabupaten", name: "Cianjur" },
    { type: "Kabupaten", name: "Cirebon" },
    { type: "Kabupaten", name: "Garut" },
    { type: "Kabupaten", name: "Indramayu" },
    { type: "Kabupaten", name: "Karawang" },
    { type: "Kabupaten", name: "Kuningan" },
    { type: "Kabupaten", name: "Majalengka" },
    { type: "Kabupaten", name: "Pangandaran" },
    { type: "Kabupaten", name: "Purwakarta" },
    { type: "Kabupaten", name: "Subang" },
    { type: "Kabupaten", name: "Sukabumi" },
    { type: "Kabupaten", name: "Sumedang" },
    { type: "Kabupaten", name: "Tasikmalaya" },
    { type: "Kota", name: "Bandung" },
    { type: "Kota", name: "Banjar" },
    { type: "Kota", name: "Bekasi" },
    { type: "Kota", name: "Bogor" },
    { type: "Kota", name: "Cimahi" },
    { type: "Kota", name: "Cirebon" },
    { type: "Kota", name: "Depok" },
    { type: "Kota", name: "Sukabumi" },
    { type: "Kota", name: "Tasikmalaya" },
  ],
  "10": [
    { type: "Kabupaten", name: "Banjarnegara" },
    { type: "Kabupaten", name: "Banyumas" },
    { type: "Kabupaten", name: "Batang" },
    { type: "Kabupaten", name: "Blora" },
    { type: "Kabupaten", name: "Boyolali" },
    { type: "Kabupaten", name: "Brebes" },
    { type: "Kabupaten", name: "Cilacap" },
    { type: "Kabupaten", name: "Demak" },
    { type: "Kabupaten", name: "Grobogan" },
    { type: "Kabupaten", name: "Jepara" },
    { type: "Kabupaten", name: "Karanganyar" },
    { type: "Kabupaten", name: "Kebumen" },
    { type: "Kabupaten", name: "Kendal" },
    { type: "Kabupaten", name: "Klaten" },
    { type: "Kabupaten", name: "Kudus" },
    { type: "Kabupaten", name: "Magelang" },
    { type: "Kabupaten", name: "Pati" },
    { type: "Kabupaten", name: "Pekalongan" },
    { type: "Kabupaten", name: "Pemalang" },
    { type: "Kabupaten", name: "Purbalingga" },
    { type: "Kabupaten", name: "Purworejo" },
    { type: "Kabupaten", name: "Rembang" },
    { type: "Kabupaten", name: "Semarang" },
    { type: "Kabupaten", name: "Sragen" },
    { type: "Kabupaten", name: "Sukoharjo" },
    { type: "Kabupaten", name: "Tegal" },
    { type: "Kabupaten", name: "Temanggung" },
    { type: "Kabupaten", name: "Wonogiri" },
    { type: "Kabupaten", name: "Wonosobo" },
    { type: "Kota", name: "Magelang" },
    { type: "Kota", name: "Pekalongan" },
    { type: "Kota", name: "Salatiga" },
    { type: "Kota", name: "Semarang" },
    { type: "Kota", name: "Surakarta" },
    { type: "Kota", name: "Tegal" },
  ],
  "11": [
    { type: "Kabupaten", name: "Bangkalan" },
    { type: "Kabupaten", name: "Banyuwangi" },
    { type: "Kabupaten", name: "Blitar" },
    { type: "Kabupaten", name: "Bojonegoro" },
    { type: "Kabupaten", name: "Bondowoso" },
    { type: "Kabupaten", name: "Gresik" },
    { type: "Kabupaten", name: "Jember" },
    { type: "Kabupaten", name: "Jombang" },
    { type: "Kabupaten", name: "Kediri" },
    { type: "Kabupaten", name: "Lamongan" },
    { type: "Kabupaten", name: "Lumajang" },
    { type: "Kabupaten", name: "Madiun" },
    { type: "Kabupaten", name: "Magetan" },
    { type: "Kabupaten", name: "Malang" },
    { type: "Kabupaten", name: "Mojokerto" },
    { type: "Kabupaten", name: "Nganjuk" },
    { type: "Kabupaten", name: "Ngawi" },
    { type: "Kabupaten", name: "Pacitan" },
    { type: "Kabupaten", name: "Pamekasan" },
    { type: "Kabupaten", name: "Pasuruan" },
    { type: "Kabupaten", name: "Ponorogo" },
    { type: "Kabupaten", name: "Probolinggo" },
    { type: "Kabupaten", name: "Sampang" },
    { type: "Kabupaten", name: "Sidoarjo" },
    { type: "Kabupaten", name: "Situbondo" },
    { type: "Kabupaten", name: "Sumenep" },
    { type: "Kabupaten", name: "Trenggalek" },
    { type: "Kabupaten", name: "Tuban" },
    { type: "Kabupaten", name: "Tulungagung" },
    { type: "Kota", name: "Batu" },
    { type: "Kota", name: "Blitar" },
    { type: "Kota", name: "Kediri" },
    { type: "Kota", name: "Madiun" },
    { type: "Kota", name: "Malang" },
    { type: "Kota", name: "Mojokerto" },
    { type: "Kota", name: "Pasuruan" },
    { type: "Kota", name: "Probolinggo" },
    { type: "Kota", name: "Surabaya" },
  ],
  "12": [
    { type: "Kabupaten", name: "Bengkayang" },
    { type: "Kabupaten", name: "Kapuas Hulu" },
    { type: "Kabupaten", name: "Kayong Utara" },
    { type: "Kabupaten", name: "Ketapang" },
    { type: "Kabupaten", name: "Kubu Raya" },
    { type: "Kabupaten", name: "Landak" },
    { type: "Kabupaten", name: "Mempawah" },
    { type: "Kabupaten", name: "Melawi" },
    { type: "Kabupaten", name: "Pontianak" },
    { type: "Kabupaten", name: "Sambas" },
    { type: "Kabupaten", name: "Sanggau" },
    { type: "Kabupaten", name: "Sekadau" },
    { type: "Kabupaten", name: "Sintang" },
    { type: "Kota", name: "Pontianak" },
    { type: "Kota", name: "Singkawang" },
  ],
  "13": [
    { type: "Kabupaten", name: "Balangan" },
    { type: "Kabupaten", name: "Banjar" },
    { type: "Kabupaten", name: "Barito Kuala" },
    { type: "Kabupaten", name: "Hulu Sungai Selatan" },
    { type: "Kabupaten", name: "Hulu Sungai Tengah" },
    { type: "Kabupaten", name: "Hulu Sungai Utara" },
    { type: "Kabupaten", name: "Kotabaru" },
    { type: "Kabupaten", name: "Tabalong" },
    { type: "Kabupaten", name: "Tanah Bumbu" },
    { type: "Kabupaten", name: "Tanah Laut" },
    { type: "Kabupaten", name: "Tapin" },
    { type: "Kota", name: "Banjarbaru" },
    { type: "Kota", name: "Banjarmasin" },
  ],
  "14": [
    { type: "Kabupaten", name: "Barito Selatan" },
    { type: "Kabupaten", name: "Barito Timur" },
    { type: "Kabupaten", name: "Barito Utara" },
    { type: "Kabupaten", name: "Gunung Mas" },
    { type: "Kabupaten", name: "Kapuas" },
    { type: "Kabupaten", name: "Katingan" },
    { type: "Kabupaten", name: "Kotawaringin Barat" },
    { type: "Kabupaten", name: "Kotawaringin Timur" },
    { type: "Kabupaten", name: "Lamandau" },
    { type: "Kabupaten", name: "Murung Raya" },
    { type: "Kabupaten", name: "Pulang Pisau" },
    { type: "Kabupaten", name: "Seruyan" },
    { type: "Kabupaten", name: "Sukamara" },
    { type: "Kota", name: "Palangka Raya" },
  ],
  "15": [
    { type: "Kabupaten", name: "Berau" },
    { type: "Kabupaten", name: "Kutai Barat" },
    { type: "Kabupaten", name: "Kutai Kartanegara" },
    { type: "Kabupaten", name: "Kutai Timur" },
    { type: "Kabupaten", name: "Mahakam Ulu" },
    { type: "Kabupaten", name: "Paser" },
    { type: "Kabupaten", name: "Penajam Paser Utara" },
    { type: "Kota", name: "Balikpapan" },
    { type: "Kota", name: "Bontang" },
    { type: "Kota", name: "Samarinda" },
  ],
  "16": [
    { type: "Kabupaten", name: "Bulungan" },
    { type: "Kabupaten", name: "Malinau" },
    { type: "Kabupaten", name: "Nunukan" },
    { type: "Kabupaten", name: "Tana Tidung" },
    { type: "Kota", name: "Tarakan" },
  ],
  "17": [
    { type: "Kabupaten", name: "Bintan" },
    { type: "Kabupaten", name: "Karimun" },
    { type: "Kabupaten", name: "Kepulauan Anambas" },
    { type: "Kabupaten", name: "Lingga" },
    { type: "Kabupaten", name: "Natuna" },
    { type: "Kota", name: "Batam" },
    { type: "Kota", name: "Tanjung Pinang" },
  ],
  "18": [
    { type: "Kabupaten", name: "Lampung Barat" },
    { type: "Kabupaten", name: "Lampung Selatan" },
    { type: "Kabupaten", name: "Lampung Tengah" },
    { type: "Kabupaten", name: "Lampung Timur" },
    { type: "Kabupaten", name: "Lampung Utara" },
    { type: "Kabupaten", name: "Mesuji" },
    { type: "Kabupaten", name: "Pesawaran" },
    { type: "Kabupaten", name: "Pesisir Barat" },
    { type: "Kabupaten", name: "Pringsewu" },
    { type: "Kabupaten", name: "Tanggamus" },
    { type: "Kabupaten", name: "Tulang Bawang" },
    { type: "Kabupaten", name: "Tulang Bawang Barat" },
    { type: "Kabupaten", name: "Way Kanan" },
    { type: "Kota", name: "Bandar Lampung" },
    { type: "Kota", name: "Metro" },
  ],
  "19": [
    { type: "Kabupaten", name: "Buru" },
    { type: "Kabupaten", name: "Buru Selatan" },
    { type: "Kabupaten", name: "Kepulauan Aru" },
    { type: "Kabupaten", name: "Maluku Barat Daya" },
    { type: "Kabupaten", name: "Maluku Tengah" },
    { type: "Kabupaten", name: "Maluku Tenggara" },
    { type: "Kabupaten", name: "Seram Bagian Barat" },
    { type: "Kabupaten", name: "Seram Bagian Timur" },
    { type: "Kabupaten", name: "Kepulauan Tanimbar" },
    { type: "Kota", name: "Ambon" },
    { type: "Kota", name: "Tual" },
  ],
  "20": [
    { type: "Kabupaten", name: "Halmahera Barat" },
    { type: "Kabupaten", name: "Halmahera Tengah" },
    { type: "Kabupaten", name: "Halmahera Timur" },
    { type: "Kabupaten", name: "Halmahera Selatan" },
    { type: "Kabupaten", name: "Halmahera Utara" },
    { type: "Kabupaten", name: "Kepulauan Sula" },
    { type: "Kabupaten", name: "Pulau Morotai" },
    { type: "Kabupaten", name: "Pulau Taliabu" },
    { type: "Kota", name: "Ternate" },
    { type: "Kota", name: "Tidore Kepulauan" },
  ],
  "21": [
    { type: "Kabupaten", name: "Aceh Barat" },
    { type: "Kabupaten", name: "Aceh Barat Daya" },
    { type: "Kabupaten", name: "Aceh Besar" },
    { type: "Kabupaten", name: "Aceh Jaya" },
    { type: "Kabupaten", name: "Aceh Selatan" },
    { type: "Kabupaten", name: "Aceh Singkil" },
    { type: "Kabupaten", name: "Aceh Tamiang" },
    { type: "Kabupaten", name: "Aceh Tengah" },
    { type: "Kabupaten", name: "Aceh Tenggara" },
    { type: "Kabupaten", name: "Aceh Timur" },
    { type: "Kabupaten", name: "Aceh Utara" },
    { type: "Kabupaten", name: "Bener Meriah" },
    { type: "Kabupaten", name: "Bireuen" },
    { type: "Kabupaten", name: "Gayo Lues" },
    { type: "Kabupaten", name: "Nagan Raya" },
    { type: "Kabupaten", name: "Pidie" },
    { type: "Kabupaten", name: "Pidie Jaya" },
    { type: "Kabupaten", name: "Simeulue" },
    { type: "Kota", name: "Banda Aceh" },
    { type: "Kota", name: "Langsa" },
    { type: "Kota", name: "Lhokseumawe" },
    { type: "Kota", name: "Sabang" },
    { type: "Kota", name: "Subulussalam" },
  ],
  "22": [
    { type: "Kabupaten", name: "Bima" },
    { type: "Kabupaten", name: "Dompu" },
    { type: "Kabupaten", name: "Lombok Barat" },
    { type: "Kabupaten", name: "Lombok Tengah" },
    { type: "Kabupaten", name: "Lombok Timur" },
    { type: "Kabupaten", name: "Lombok Utara" },
    { type: "Kabupaten", name: "Sumbawa" },
    { type: "Kabupaten", name: "Sumbawa Barat" },
    { type: "Kota", name: "Bima" },
    { type: "Kota", name: "Mataram" },
  ],
  "23": [
    { type: "Kabupaten", name: "Alor" },
    { type: "Kabupaten", name: "Belu" },
    { type: "Kabupaten", name: "Ende" },
    { type: "Kabupaten", name: "Flores Timur" },
    { type: "Kabupaten", name: "Kupang" },
    { type: "Kabupaten", name: "Lembata" },
    { type: "Kabupaten", name: "Manggarai" },
    { type: "Kabupaten", name: "Manggarai Barat" },
    { type: "Kabupaten", name: "Manggarai Timur" },
    { type: "Kabupaten", name: "Nagekeo" },
    { type: "Kabupaten", name: "Ngada" },
    { type: "Kabupaten", name: "Rote Ndao" },
    { type: "Kabupaten", name: "Sabu Raijua" },
    { type: "Kabupaten", name: "Sikka" },
    { type: "Kabupaten", name: "Sumba Barat" },
    { type: "Kabupaten", name: "Sumba Barat Daya" },
    { type: "Kabupaten", name: "Sumba Tengah" },
    { type: "Kabupaten", name: "Sumba Timur" },
    { type: "Kabupaten", name: "Timor Tengah Selatan" },
    { type: "Kabupaten", name: "Timor Tengah Utara" },
    { type: "Kota", name: "Kupang" },
  ],
  "24": [
    { type: "Kabupaten", name: "Asmat" },
    { type: "Kabupaten", name: "Biak Numfor" },
    { type: "Kabupaten", name: "Boven Digoel" },
    { type: "Kabupaten", name: "Deiyai" },
    { type: "Kabupaten", name: "Dogiyai" },
    { type: "Kabupaten", name: "Intan Jaya" },
    { type: "Kabupaten", name: "Jayapura" },
    { type: "Kabupaten", name: "Jayawijaya" },
    { type: "Kabupaten", name: "Keerom" },
    { type: "Kabupaten", name: "Kepulauan Yapen" },
    { type: "Kabupaten", name: "Lanny Jaya" },
    { type: "Kabupaten", name: "Mamberamo Raya" },
    { type: "Kabupaten", name: "Mamberamo Tengah" },
    { type: "Kabupaten", name: "Mappi" },
    { type: "Kabupaten", name: "Merauke" },
    { type: "Kabupaten", name: "Mimika" },
    { type: "Kabupaten", name: "Nabire" },
    { type: "Kabupaten", name: "Nduga" },
    { type: "Kabupaten", name: "Paniai" },
    { type: "Kabupaten", name: "Pegunungan Bintang" },
    { type: "Kabupaten", name: "Puncak" },
    { type: "Kabupaten", name: "Puncak Jaya" },
    { type: "Kabupaten", name: "Sarmi" },
    { type: "Kabupaten", name: "Supiori" },
    { type: "Kabupaten", name: "Tolikara" },
    { type: "Kabupaten", name: "Waropen" },
    { type: "Kabupaten", name: "Yahukimo" },
    { type: "Kabupaten", name: "Yalimo" },
    { type: "Kota", name: "Jayapura" },
  ],
  "25": [
    { type: "Kabupaten", name: "Fakfak" },
    { type: "Kabupaten", name: "Kaimana" },
    { type: "Kabupaten", name: "Manokwari" },
    { type: "Kabupaten", name: "Manokwari Selatan" },
    { type: "Kabupaten", name: "Maybrat" },
    { type: "Kabupaten", name: "Pegunungan Arfak" },
    { type: "Kabupaten", name: "Raja Ampat" },
    { type: "Kabupaten", name: "Sorong" },
    { type: "Kabupaten", name: "Sorong Selatan" },
    { type: "Kabupaten", name: "Tambrauw" },
    { type: "Kabupaten", name: "Teluk Bintuni" },
    { type: "Kabupaten", name: "Teluk Wondama" },
    { type: "Kota", name: "Sorong" },
  ],
  "26": [
    { type: "Kabupaten", name: "Bengkalis" },
    { type: "Kabupaten", name: "Indragiri Hilir" },
    { type: "Kabupaten", name: "Indragiri Hulu" },
    { type: "Kabupaten", name: "Kampar" },
    { type: "Kabupaten", name: "Kepulauan Meranti" },
    { type: "Kabupaten", name: "Kuantan Singingi" },
    { type: "Kabupaten", name: "Pelalawan" },
    { type: "Kabupaten", name: "Rokan Hilir" },
    { type: "Kabupaten", name: "Rokan Hulu" },
    { type: "Kabupaten", name: "Siak" },
    { type: "Kota", name: "Dumai" },
    { type: "Kota", name: "Pekanbaru" },
  ],
  "27": [
    { type: "Kabupaten", name: "Majene" },
    { type: "Kabupaten", name: "Mamasa" },
    { type: "Kabupaten", name: "Mamuju" },
    { type: "Kabupaten", name: "Mamuju Tengah" },
    { type: "Kabupaten", name: "Pasangkayu" },
    { type: "Kabupaten", name: "Polewali Mandar" },
  ],
  "28": [
    { type: "Kabupaten", name: "Bantaeng" },
    { type: "Kabupaten", name: "Barru" },
    { type: "Kabupaten", name: "Bone" },
    { type: "Kabupaten", name: "Bulukumba" },
    { type: "Kabupaten", name: "Enrekang" },
    { type: "Kabupaten", name: "Gowa" },
    { type: "Kabupaten", name: "Jeneponto" },
    { type: "Kabupaten", name: "Kepulauan Selayar" },
    { type: "Kabupaten", name: "Luwu" },
    { type: "Kabupaten", name: "Luwu Timur" },
    { type: "Kabupaten", name: "Luwu Utara" },
    { type: "Kabupaten", name: "Maros" },
    { type: "Kabupaten", name: "Pangkajene dan Kepulauan" },
    { type: "Kabupaten", name: "Pinrang" },
    { type: "Kabupaten", name: "Sidenreng Rappang" },
    { type: "Kabupaten", name: "Sinjai" },
    { type: "Kabupaten", name: "Soppeng" },
    { type: "Kabupaten", name: "Takalar" },
    { type: "Kabupaten", name: "Tana Toraja" },
    { type: "Kabupaten", name: "Toraja Utara" },
    { type: "Kabupaten", name: "Wajo" },
    { type: "Kota", name: "Makassar" },
    { type: "Kota", name: "Palopo" },
    { type: "Kota", name: "Parepare" },
  ],
  "29": [
    { type: "Kabupaten", name: "Banggai" },
    { type: "Kabupaten", name: "Banggai Kepulauan" },
    { type: "Kabupaten", name: "Banggai Laut" },
    { type: "Kabupaten", name: "Buol" },
    { type: "Kabupaten", name: "Donggala" },
    { type: "Kabupaten", name: "Morowali" },
    { type: "Kabupaten", name: "Morowali Utara" },
    { type: "Kabupaten", name: "Parigi Moutong" },
    { type: "Kabupaten", name: "Poso" },
    { type: "Kabupaten", name: "Sigi" },
    { type: "Kabupaten", name: "Tojo Una-Una" },
    { type: "Kabupaten", name: "Tolitoli" },
    { type: "Kota", name: "Palu" },
  ],
  "30": [
    { type: "Kabupaten", name: "Bombana" },
    { type: "Kabupaten", name: "Buton" },
    { type: "Kabupaten", name: "Buton Selatan" },
    { type: "Kabupaten", name: "Buton Tengah" },
    { type: "Kabupaten", name: "Buton Utara" },
    { type: "Kabupaten", name: "Kolaka" },
    { type: "Kabupaten", name: "Kolaka Timur" },
    { type: "Kabupaten", name: "Kolaka Utara" },
    { type: "Kabupaten", name: "Konawe" },
    { type: "Kabupaten", name: "Konawe Kepulauan" },
    { type: "Kabupaten", name: "Konawe Selatan" },
    { type: "Kabupaten", name: "Konawe Utara" },
    { type: "Kabupaten", name: "Muna" },
    { type: "Kabupaten", name: "Muna Barat" },
    { type: "Kabupaten", name: "Wakatobi" },
    { type: "Kota", name: "Bau-Bau" },
    { type: "Kota", name: "Kendari" },
  ],
  "31": [
    { type: "Kabupaten", name: "Bolaang Mongondow" },
    { type: "Kabupaten", name: "Bolaang Mongondow Selatan" },
    { type: "Kabupaten", name: "Bolaang Mongondow Timur" },
    { type: "Kabupaten", name: "Bolaang Mongondow Utara" },
    { type: "Kabupaten", name: "Kepulauan Sangihe" },
    { type: "Kabupaten", name: "Kepulauan Siau Tagulandang Biaro" },
    { type: "Kabupaten", name: "Kepulauan Talaud" },
    { type: "Kabupaten", name: "Minahasa" },
    { type: "Kabupaten", name: "Minahasa Selatan" },
    { type: "Kabupaten", name: "Minahasa Tenggara" },
    { type: "Kabupaten", name: "Minahasa Utara" },
    { type: "Kota", name: "Bitung" },
    { type: "Kota", name: "Kotamobagu" },
    { type: "Kota", name: "Manado" },
    { type: "Kota", name: "Tomohon" },
  ],
  "32": [
    { type: "Kabupaten", name: "Agam" },
    { type: "Kabupaten", name: "Dharmasraya" },
    { type: "Kabupaten", name: "Kepulauan Mentawai" },
    { type: "Kabupaten", name: "Lima Puluh Kota" },
    { type: "Kabupaten", name: "Padang Pariaman" },
    { type: "Kabupaten", name: "Pasaman" },
    { type: "Kabupaten", name: "Pasaman Barat" },
    { type: "Kabupaten", name: "Pesisir Selatan" },
    { type: "Kabupaten", name: "Sijunjung" },
    { type: "Kabupaten", name: "Solok" },
    { type: "Kabupaten", name: "Solok Selatan" },
    { type: "Kabupaten", name: "Tanah Datar" },
    { type: "Kota", name: "Bukittinggi" },
    { type: "Kota", name: "Padang" },
    { type: "Kota", name: "Padang Panjang" },
    { type: "Kota", name: "Pariaman" },
    { type: "Kota", name: "Payakumbuh" },
    { type: "Kota", name: "Sawahlunto" },
    { type: "Kota", name: "Solok" },
  ],
  "33": [
    { type: "Kabupaten", name: "Banyuasin" },
    { type: "Kabupaten", name: "Empat Lawang" },
    { type: "Kabupaten", name: "Lahat" },
    { type: "Kabupaten", name: "Muara Enim" },
    { type: "Kabupaten", name: "Musi Banyuasin" },
    { type: "Kabupaten", name: "Musi Rawas" },
    { type: "Kabupaten", name: "Musi Rawas Utara" },
    { type: "Kabupaten", name: "Ogan Ilir" },
    { type: "Kabupaten", name: "Ogan Komering Ilir" },
    { type: "Kabupaten", name: "Ogan Komering Ulu" },
    { type: "Kabupaten", name: "Ogan Komering Ulu Selatan" },
    { type: "Kabupaten", name: "Ogan Komering Ulu Timur" },
    { type: "Kabupaten", name: "Penukal Abab Lematang Ilir" },
    { type: "Kota", name: "Lubuklinggau" },
    { type: "Kota", name: "Pagar Alam" },
    { type: "Kota", name: "Palembang" },
    { type: "Kota", name: "Prabumulih" },
  ],
  "34": [
    { type: "Kabupaten", name: "Asahan" },
    { type: "Kabupaten", name: "Batu Bara" },
    { type: "Kabupaten", name: "Dairi" },
    { type: "Kabupaten", name: "Deli Serdang" },
    { type: "Kabupaten", name: "Humbang Hasundutan" },
    { type: "Kabupaten", name: "Karo" },
    { type: "Kabupaten", name: "Labuhan Batu" },
    { type: "Kabupaten", name: "Labuhan Batu Selatan" },
    { type: "Kabupaten", name: "Labuhan Batu Utara" },
    { type: "Kabupaten", name: "Langkat" },
    { type: "Kabupaten", name: "Mandailing Natal" },
    { type: "Kabupaten", name: "Nias" },
    { type: "Kabupaten", name: "Nias Barat" },
    { type: "Kabupaten", name: "Nias Selatan" },
    { type: "Kabupaten", name: "Nias Utara" },
    { type: "Kabupaten", name: "Padang Lawas" },
    { type: "Kabupaten", name: "Padang Lawas Utara" },
    { type: "Kabupaten", name: "Pakpak Bharat" },
    { type: "Kabupaten", name: "Samosir" },
    { type: "Kabupaten", name: "Serdang Bedagai" },
    { type: "Kabupaten", name: "Simalungun" },
    { type: "Kabupaten", name: "Tapanuli Selatan" },
    { type: "Kabupaten", name: "Tapanuli Tengah" },
    { type: "Kabupaten", name: "Tapanuli Utara" },
    { type: "Kabupaten", name: "Toba" },
    { type: "Kota", name: "Binjai" },
    { type: "Kota", name: "Gunungsitoli" },
    { type: "Kota", name: "Medan" },
    { type: "Kota", name: "Padangsidimpuan" },
    { type: "Kota", name: "Pematangsiantar" },
    { type: "Kota", name: "Sibolga" },
    { type: "Kota", name: "Tanjungbalai" },
    { type: "Kota", name: "Tebing Tinggi" },
  ],
};

function slugify(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .toLowerCase();
}

export const STATIC_CITIES: Record<string, StaticCity[]> = Object.fromEntries(
  Object.entries(RAW_STATIC_CITIES).map(([provinceId, cities]) => {
    const provinceName = STATIC_PROVINCES.find((province) => province.id === provinceId)?.name ?? "";
    return [
      provinceId,
      cities.map((city) => ({
        id: `${provinceId}-${slugify(`${city.type}-${city.name}`)}`,
        provinceId,
        provinceName,
        type: city.type,
        name: city.name,
      })),
    ];
  }),
);

export function getStaticCitiesByProvince(provinceId: string): StaticCity[] {
  return STATIC_CITIES[provinceId] ?? [];
}

export const STATIC_CITIES_FLAT: StaticCity[] = Object.values(STATIC_CITIES).flat();
