CREATE TYPE "StoreBadge" AS ENUM ('BASIC', 'STAR', 'STAR_PLUS', 'MALL', 'PREMIUM');

ALTER TABLE "User"
  ADD COLUMN "storeBadge" "StoreBadge" NOT NULL DEFAULT 'BASIC',
  ADD COLUMN "storeIsOnline" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "storeFollowers" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "storeFollowing" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "storeRating" DOUBLE PRECISION,
  ADD COLUMN "storeRatingCount" INTEGER NOT NULL DEFAULT 0;
